/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["setupVault"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/session/unlock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["unlockVault"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/session/lock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["lockVault"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/session/recover": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["recoverVault"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/credentials": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listCredentials"];
    put?: never;
    post: operations["createCredential"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/credentials/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteCredential"];
    options?: never;
    head?: never;
    patch: operations["updateCredential"];
    trace?: never;
  };
  "/credentials/{id}/secret": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    /** @description Returns seed material only to an authenticated browser session. Bearer API keys are never accepted. */
    get: operations["revealCredentialSecret"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/credentials/{id}/code": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    get: operations["getCredentialCode"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/codes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getCodes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/groups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listGroups"];
    put?: never;
    post: operations["createGroup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/groups/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteGroup"];
    options?: never;
    head?: never;
    patch: operations["updateGroup"];
    trace?: never;
  };
  "/settings/api-keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listAPIKeys"];
    put?: never;
    post: operations["createAPIKey"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/settings/api-keys/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteAPIKey"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/settings/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["changePassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/settings/recovery/rotate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["rotateRecovery"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["exportBackup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["previewBackup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/{id}/apply": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["applyBackup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Status: {
      setup: boolean;
      locked: boolean;
      authenticated: boolean;
      csrfToken?: string;
      version: string;
      /** @constant */
      testOnly: true;
    };
    PasswordInput: {
      password: string;
    };
    RecoveryInput: {
      recoveryKey: string;
      password: string;
    };
    Session: {
      csrfToken: string;
    };
    RecoveryKey: {
      recoveryKey: string;
    };
    RecoverySession: {
      csrfToken: string;
      recoveryKey: string;
    };
    CredentialInput: {
      /** @enum {string} */
      source: "manual" | "uri" | "generate";
      uri?: string;
      issuer?: string;
      account: string;
      secret?: string;
      algorithm: components["schemas"]["Algorithm"];
      /** @enum {integer} */
      digits: 6 | 8;
      period: number;
      favorite: boolean;
      /** Format: uuid */
      groupId?: string;
      tags: string[];
      notes: string;
    };
    Credential: {
      /** Format: uuid */
      id: string;
      issuer: string;
      account: string;
      algorithm: components["schemas"]["Algorithm"];
      /** @enum {integer} */
      digits: 6 | 8;
      period: number;
      favorite: boolean;
      /** Format: uuid */
      groupId?: string;
      tags: string[];
      notes: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CredentialsResponse: {
      credentials: components["schemas"]["Credential"][];
    };
    /** @enum {string} */
    Algorithm: "SHA1" | "SHA256" | "SHA512";
    Secret: {
      secret: string;
      /** Format: uri */
      uri: string;
    };
    CurrentCode: {
      /** Format: uuid */
      credentialId: string;
      code: string;
      /** Format: date-time */
      validFrom: string;
      /** Format: date-time */
      validUntil: string;
    };
    CodesResponse: {
      /** Format: date-time */
      serverTime: string;
      codes: components["schemas"]["CurrentCode"][];
    };
    GroupInput: {
      name: string;
      color: string;
    };
    Group: {
      /** Format: uuid */
      id: string;
      name: string;
      color: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    GroupsResponse: {
      groups: components["schemas"]["Group"][];
    };
    APIKeyInput: {
      name: string;
    };
    APIKey: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastUsed?: string;
    };
    CreatedAPIKey: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastUsed?: string;
      key: string;
    };
    APIKeysResponse: {
      apiKeys: components["schemas"]["APIKey"][];
    };
    PasswordChangeInput: {
      current: string;
      replacement: string;
    };
    BackupPreviewInput: {
      /** Format: binary */
      file: string;
      password: string;
    };
    BackupPreview: {
      /** Format: uuid */
      id: string;
      credentials: number;
      groups: number;
      duplicates: number;
      nameConflicts: number;
      /** Format: date-time */
      createdAt: string;
    };
    BackupApplyInput: {
      /** @enum {string} */
      mode: "merge" | "replace";
    };
    Error: {
      error: {
        /** @enum {string} */
        code:
          | "invalid_json"
          | "invalid_content_type"
          | "unauthorized"
          | "csrf_failed"
          | "invalid_host"
          | "invalid_origin"
          | "not_found"
          | "conflict"
          | "not_setup"
          | "validation_failed"
          | "vault_locked"
          | "rate_limited";
        message: string;
      };
    };
  };
  responses: {
    /** @description Request failed */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Unlock or recovery attempts are temporarily rate limited */
    RateLimited: {
      headers: {
        /** @description Seconds before retrying */
        "Retry-After"?: number;
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    ID: string;
    /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
    CSRFToken: string;
  };
  requestBodies: {
    Password: {
      content: {
        "application/json": components["schemas"]["PasswordInput"];
      };
    };
    Credential: {
      content: {
        "application/json": components["schemas"]["CredentialInput"];
      };
    };
    Group: {
      content: {
        "application/json": components["schemas"]["GroupInput"];
      };
    };
  };
  headers: {
    /** @description HttpOnly, SameSite=Strict browser session cookie */
    SessionCookie: string;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lifecycle and session status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Status"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  setupVault: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: components["requestBodies"]["Password"];
    responses: {
      /** @description Vault created; recovery key is returned once */
      201: {
        headers: {
          "Set-Cookie": components["headers"]["SessionCookie"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecoverySession"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  unlockVault: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: components["requestBodies"]["Password"];
    responses: {
      /** @description Vault unlocked */
      200: {
        headers: {
          "Set-Cookie": components["headers"]["SessionCookie"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      429: components["responses"]["RateLimited"];
      default: components["responses"]["Error"];
    };
  };
  lockVault: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Vault locked and all sessions revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  recoverVault: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecoveryInput"];
      };
    };
    responses: {
      /** @description Password reset and recovery key rotated */
      200: {
        headers: {
          "Set-Cookie": components["headers"]["SessionCookie"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecoverySession"];
        };
      };
      429: components["responses"]["RateLimited"];
      default: components["responses"]["Error"];
    };
  };
  listCredentials: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Seed-free credential metadata */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CredentialsResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  createCredential: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: components["requestBodies"]["Credential"];
    responses: {
      /** @description Credential created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Credential"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  deleteCredential: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Credential deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  updateCredential: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody: components["requestBodies"]["Credential"];
    responses: {
      /** @description Credential updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Credential"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  revealCredentialSecret: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Explicit seed reveal */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Secret"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getCredentialCode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current code and server-derived validity interval */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentCode"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  getCodes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All current codes generated at one server instant */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CodesResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listGroups: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Groups */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupsResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  createGroup: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: components["requestBodies"]["Group"];
    responses: {
      /** @description Group created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  deleteGroup: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Group deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  updateGroup: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody: components["requestBodies"]["Group"];
    responses: {
      /** @description Group updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  listAPIKeys: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Named read-only API keys without plaintext key material */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["APIKeysResponse"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  createAPIKey: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["APIKeyInput"];
      };
    };
    responses: {
      /** @description API key created; plaintext key material is returned once */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatedAPIKey"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  deleteAPIKey: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API key revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordChangeInput"];
      };
    };
    responses: {
      /** @description Password changed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
  rotateRecovery: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recovery key rotated; new value is returned once */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecoveryKey"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  exportBackup: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: components["requestBodies"]["Password"];
    responses: {
      /** @description Encrypted `.ltotp` backup */
      200: {
        headers: {
          /** @description Attachment filename */
          "Content-Disposition"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/vnd.local-totp.backup+json": string;
        };
      };
      default: components["responses"]["Error"];
    };
  };
  previewBackup: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["BackupPreviewInput"];
      };
    };
    responses: {
      /** @description Validated import preview with a five-minute identifier */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackupPreview"];
        };
      };
      default: components["responses"]["Error"];
    };
  };
  applyBackup: {
    parameters: {
      query?: never;
      header: {
        /** @description Token returned by setup, unlock, recover, or status for the authenticated session. */
        "X-CSRF-Token": components["parameters"]["CSRFToken"];
      };
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BackupApplyInput"];
      };
    };
    responses: {
      /** @description Backup applied */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Error"];
    };
  };
}
