/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["setupVault"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/session/unlock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["unlockVault"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/session/lock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["lockVault"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/session/recover": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["recoverVault"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/credentials": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listCredentials"];
    put?: never;
    post: operations["createCredential"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/credentials/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteCredential"];
    options?: never;
    head?: never;
    patch: operations["updateCredential"];
    trace?: never;
  };
  "/credentials/{id}/secret": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    get: operations["revealCredentialSecret"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/credentials/{id}/code": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    get: operations["getCredentialCode"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/codes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getCodes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/groups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listGroups"];
    put?: never;
    post: operations["createGroup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/groups/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteGroup"];
    options?: never;
    head?: never;
    patch: operations["updateGroup"];
    trace?: never;
  };
  "/settings/api-keys": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listAPIKeys"];
    put?: never;
    post: operations["createAPIKey"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/settings/api-keys/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteAPIKey"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/settings/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["changePassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/settings/recovery/rotate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["rotateRecovery"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["exportBackup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["previewBackup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/backups/{id}/apply": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["applyBackup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Status: {
      setup: boolean;
      locked: boolean;
      authenticated: boolean;
      csrfToken?: string;
      version: string;
      /** @constant */
      testOnly: true;
    };
    PasswordInput: {
      password: string;
    };
    CredentialInput: {
      /** @enum {string} */
      source: "manual" | "uri" | "generate";
      uri?: string;
      issuer?: string;
      account: string;
      secret?: string;
      algorithm: components["schemas"]["Algorithm"];
      digits: number;
      period: number;
      favorite: boolean;
      groupId?: string;
      tags: string[];
      notes: string;
    };
    Credential: {
      /** Format: uuid */
      id: string;
      issuer: string;
      account: string;
      algorithm: components["schemas"]["Algorithm"];
      digits: number;
      period: number;
      favorite: boolean;
      groupId?: string;
      tags: string[];
      notes: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** @enum {string} */
    Algorithm: "SHA1" | "SHA256" | "SHA512";
    Secret: {
      secret: string;
      uri: string;
    };
    CurrentCode: {
      /** Format: uuid */
      credentialId: string;
      code: string;
      /** Format: date-time */
      validFrom: string;
      /** Format: date-time */
      validUntil: string;
    };
    CodesResponse: {
      /** Format: date-time */
      serverTime: string;
      codes: components["schemas"]["CurrentCode"][];
    };
    Error: {
      error: {
        code: string;
        message: string;
        details?: unknown;
      };
    };
  };
  responses: {
    /** @description Error */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    ID: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lifecycle status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Status"];
        };
      };
    };
  };
  setupVault: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordInput"];
      };
    };
    responses: {
      /** @description Vault created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      422: components["responses"]["Error"];
    };
  };
  unlockVault: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordInput"];
      };
    };
    responses: {
      /** @description Unlocked */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Error"];
    };
  };
  lockVault: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Locked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  recoverVault: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recovered with a rotated recovery key */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listCredentials: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Credential metadata */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            credentials: components["schemas"]["Credential"][];
          };
        };
      };
    };
  };
  createCredential: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CredentialInput"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Credential"];
        };
      };
    };
  };
  deleteCredential: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateCredential: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  revealCredentialSecret: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Explicit seed reveal */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Secret"];
        };
      };
    };
  };
  getCredentialCode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current code */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentCode"];
        };
      };
    };
  };
  getCodes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All current codes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CodesResponse"];
        };
      };
    };
  };
  listGroups: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Groups */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createGroup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteGroup: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateGroup: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listAPIKeys: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Named keys */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createAPIKey: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Created; plaintext returned once */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteAPIKey: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Changed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  rotateRecovery: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Rotated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  exportBackup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Encrypted .ltotp file */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  previewBackup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Import preview */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  applyBackup: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["ID"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Applied */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
